server.port=5000
spring.application.name=similar-products
similar-products.client.base-url=http://localhost:3001
similar-products.client.response-timeout=10s
similar-products.client.connect-timeout-millis=2000
similar-products.client.max-concurrency=3
